name: flutter_drawer_plus
description: Drawer Plus is an easy way to create an internal side section (left/right) where you can insert a list menu or other.
version: 1.0.0+2
repository: https://github.com/LuisGrt/flutter_drawer_plus
homepage: https://pub.dev/packages/flutter_drawer_plus

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
